type Register = {
   last_name: string;
   first_name: string;
   middle_name: string;
   age: string;
   gender: string;
   contact_no: string;
   email: string;
   birthday: string;
   marital_status: string;
   past_medical: string;
   vital_sign: string;
   diagnosis: string;
   treatment: string;
   birth_certificate: string;
   physical_examination: string;
   profile: string;
   address: string;
   barangay: string;
};
